development:
  client_id: 'KD2J2MZSPROQT0OGZ3PH2USN4NUBHWXOUI1PCO3LJYLGXHR2'
  client_secret: 'MJS4ETVJGHVDMEDQSBWJTW1F0BIA5YZILU50EGISDJZUS1ML'

test:
  client_id: 'KD2J2MZSPROQT0OGZ3PH2USN4NUBHWXOUI1PCO3LJYLGXHR2'
  client_secret: 'MJS4ETVJGHVDMEDQSBWJTW1F0BIA5YZILU50EGISDJZUS1ML'

production:
  client_id: 
  client_secret: 